[phases.setup]
cmds = [
  "cd testerqa && yarn install",
  "cd backend && ./mvnw clean package -DskipTests"
]

[phases.build]
cmds = [
  "cd testerqa && yarn build",
  "cd backend && ./mvnw package -DskipTests"
]

[phases.start]
cmd = "cd backend && java -jar target/*.jar --server.port=$PORT"

[env]
PORT = "8081"
NODE_ENV = "production"
SPRING_PROFILES_ACTIVE = "prod"