[phases.setup]
cmds = [
  # Instala Node.js e Yarn corretamente
  "corepack enable",
  "corepack prepare yarn@stable --activate",
  "corepack install",
  "yarn --version",

  # Frontend
  "cd testerqa && yarn install --frozen-lockfile --production=false",
  "cd testerqa && yarn add vite",

  # Backend
  "cd backend && chmod +x mvnw && ./mvnw clean install -DskipTests"
]

[phases.build]
cmds = [
  # Build do frontend
  "cd testerqa && yarn build",
  
  # Build do backend
  "cd backend && ./mvnw package -DskipTests"
]

[phases.start]
cmd = "cd backend && java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar target/*.jar --server.port=${PORT}"

[env]
# Versões
NODE_VERSION = "20"
JAVA_VERSION = "21"

# Configurações do Spring
SPRING_PROFILES_ACTIVE = "prod"
SPRING_DATASOURCE_URL = { from = "DATABASE_URL" }
SPRING_DATASOURCE_USERNAME = { from = "PGUSER" }
SPRING_DATASOURCE_PASSWORD = { from = "PGPASSWORD", secret = true }

# Frontend
NODE_ENV = "production"