[phases.setup]
cmds = [
  # Frontend (Vite/Node.js)
  "cd testerqa && yarn install --frozen-lockfile --production=false && yarn add vite",
  
  # Backend (Spring Boot)
  "cd backend && chmod +x mvnw && ./mvnw clean install -DskipTests"
]

[phases.build]
cmds = [
  # Frontend - Build de produção
  "cd testerqa && yarn build",
  
  # Backend - Gerar .jar
  "cd backend && ./mvnw package -DskipTests"
]

[phases.start]
cmd = "cd backend && java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar target/*.jar --server.port=${PORT}"

[env]
# Configurações do Spring
SPRING_PROFILES_ACTIVE = "prod"
SPRING_DATASOURCE_URL = { from = "DATABASE_URL" }
SPRING_DATASOURCE_USERNAME = { from = "PGUSER" }
SPRING_DATASOURCE_PASSWORD = { from = "PGPASSWORD", secret = true }

# Segurança
TOKEN_SECRET = { secret = true }  # Configure no painel do Railway

# Frontend
NODE_ENV = "production"