[phases.setup]
cmds = [
  # Garante que o Corepack e o Yarn estejam disponíveis
  "corepack enable",
  "corepack prepare yarn@stable --activate",
  "yarn set version stable",
  "yarn --version",

  # Instala dependências do frontend
  "cd testerqa && yarn install --frozen-lockfile --production=false",
  "cd testerqa && yarn add vite",

  # Instala dependências do backend
  "cd backend && chmod +x mvnw && ./mvnw clean install -DskipTests"
]

[phases.build]
cmds = [
  # Build do frontend
  "cd testerqa && yarn build",
  
  # Build do backend
  "cd backend && ./mvnw package -DskipTests"
]

[phases.start]
cmd = "cd backend && java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar target/*.jar --server.port=${PORT}"

[env]
# Versões das tecnologias
NODE_VERSION = "22"
JAVA_VERSION = "21"

# Configurações do Spring Boot
SPRING_PROFILES_ACTIVE = "prod"
SPRING_DATASOURCE_URL = { from = "DATABASE_URL" }
SPRING_DATASOURCE_USERNAME = { from = "PGUSER" }
SPRING_DATASOURCE_PASSWORD = { from = "PGPASSWORD", secret = true }

# Configuração do Frontend
NODE_ENV = "production"
