[phases.setup]
cmds = [
  # Frontend (instalação local sem privilégios) --
  "cd testerqa && npm install -g yarn && yarn install --frozen-lockfile",
  
  # Backend
  "cd backend && chmod +x mvnw && ./mvnw clean install -DskipTests"
]

[phases.build]
cmds = [
  # Build do frontend
  "cd testerqa && yarn build",
  
  # Integração com Spring Boot
  "mkdir -p backend/src/main/resources/static",
  "cp -R testerqa/dist/* backend/src/main/resources/static/",
  
  # Build final teste
  "cd backend && ./mvnw package -DskipTests"
]

[phases.start]
cmd = "cd backend && java -jar target/*.jar --server.port=${PORT}"
