[phases.setup]
cmds = [
  "cd testerqa && yarn install --frozen-lockfile",
  "cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests"
]

[phases.build]
cmds = [
  "cd testerqa && yarn build",
  "cd backend && ./mvnw package -DskipTests"
]

[phases.start]
cmd = "cd backend && java -Dserver.port=${PORT:-8081} -jar target/demo-0.0.1-SNAPSHOT.jar"

[env]
PORT = "8081"
NODE_ENV = "production"
SPRING_PROFILES_ACTIVE = "prod"
TOKEN_SECRET = "dGhpcy1lcy11bWEtY2hhdmUtc2Vnby1wYXJhLWp3dC1jb20tNjQtY2FyYWN0ZXJlcw=="
DATABASE_URL = ""
DB_USERNAME = ""
DB_PASSWORD = ""