[phases.setup]
cmds = [
  # Frontend (React/Vite/TypeScript)
  "cd testerqa && yarn install --frozen-lockfile",
  
  # Backend (Spring Boot)
  "cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests"
]

[phases.build]
cmds = [
  # Build do frontend
  "cd testerqa && yarn build",
  
  # Build do backend
  "cd backend && ./mvnw package -DskipTests"
]

[phases.start]
cmd = "cd backend && java -Dserver.port=$PORT -jar target/*.jar"